name: Pre-Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      runner:
        type: string
        default: ubuntu-latest

jobs:
  deploy:
    name: Pre-Deploy
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}

    steps:
      - id: context
        name: Context
        uses: actions/github-script@v7
        with:
          script: console.log(context)
