name: Sample Required Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  context:
    name: Context
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: console.log(context)

  setup:
    name: Setup
    runs-on:
      - ubuntu-latest

    outputs:
      workflow: ${{ steps.workflow.outputs.ref }}
      environments: ${{ steps.envs.outputs.list }}

    steps:
      - id: envs
        name: Environments
        run: |
          # Build up environments list
          format_list () {
            # Normalize comma-separated list to JSON
            local INPUT=$1; shift;
            local LIST=;
            IFS=',' read -r -a ITEMS <<< $INPUT;
            for i in ${ITEMS[@]};
            do
              LIST="${LIST}\"${i}\",";
            done
            local OUTPUT="[${LIST%?}]"; # Drop off the last comma
            echo $OUTPUT;
          }
          echo "list=$(format_list dev,test,stage,prod)" | tee -a $GITHUB_OUTPUT;
          cat $GITHUB_OUTPUT;

      - id: workflow
        name: Workflow
        run: |
          # Setup workflow to run
          echo "ref=EPAM-SP/test-public-workflows/.github/workflows/deploy.yml@main" | tee -a $GITHUB_OUTPUT;
          cat $GITHUB_OUTPUT;
  dev:
    # strategy:
    #   matrix:
    #     environment: ${{ fromJSON(needs.setup.outputs.environments) }}
    name: Dev
    uses: EPAM-SP/test-private-workflows/.github/workflows/deploy.yml@main
    with:
      environment: dev
    needs: 
      - setup

  test:
    name: Test
    uses: EPAM-SP/test-private-workflows/.github/workflows/deploy.yml@main
    with:
      environment: test
    needs:
      - dev

  stage:
    name: Stage
    uses: EPAM-SP/test-private-workflows/.github/workflows/deploy.yml@main
    with:
      environment: stage
    needs:
      - test

  prod:
    name: Prod
    uses: EPAM-SP/test-private-workflows/.github/workflows/deploy.yml@main
    with:
      environment: prod
    needs:
      - stage
